### ISSUE TITLE
Please separate your logic from script.js

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/LoSo#11]
Try to keep in one file logic for one functionality . The file should be simple as much as possible . 
You don't need to write comments to separate logic blocks . Instead create files . 
<img width="741" alt="screen shot 2018-04-03 at 11 53 05 am" src="https://user-images.githubusercontent.com/2377964/38239554-bc9e2d4e-3735-11e8-9480-7c3ccdfc49da.png">

**Comment by Stanislava15** [comment]
Got it!
Done!

I had 1 .js file named "scripts"....Now I have 4 .js file (scripts, scroll, mob-nav, maps). Everyone I included to html file.
