### ISSUE TITLE
Another problems

### ISSUE THREAD

**Issue by davidrud135** [Stanislava15/LoSo#13]
1. Meta
In your meta tag you have`content="width=device initial-scale=1"`,
but  it should be `content="width=device-width, initial-scale=1"`
2. Testimonial slider
Your HTML: `<li data-target="carousel-testimonial" data-slider-to="0"></li>`
  - You forgot to pass id symbols ("#") to `data-target`
  - Mistakes in `data-slider-to`, should be `data-slide-to`
  So, correct HTML (do not forget to apply this fixes to all `<li>` tags): 
  `<li data-target="#carousel-testimonial" data-slide-to="0"></li>`

**Comment by lapachuka** [comment]
@davidrud135 please be focused on your own project ;)
