### ISSUE TITLE
When click on `I'm hungry` button the error is appeared in console

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/LoSo#2]
scripts.js:14 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLAnchorElement.<anonymous> (scripts.js:14)
    at HTMLAnchorElement.dispatch (jquery.min.js:2)
    at HTMLAnchorElement.y.handle (jquery.min.js:2)

**Comment by Stanislava15** [comment]
Hi! 
First of all,
All issues, which you've wrote here, are about prodject "omnifood", which is in repository  "omnifood".
Current repository "loso1" - is another project =)


I've corrected my code, so, I don't see that errors now. Please, check this page)

**Comment by lapachuka** [comment]
True. We are working now with Omnifood
