### ISSUE TITLE
3 files can't connect to the project

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/LoSo#3]
GET file://cdn.jsdelivr.net/respond/1.4.2/respond.min.js net::ERR_FILE_NOT_FOUND
index.html:439 GET file://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js net::ERR_FILE_NOT_FOUND
index.html:440 GET file://cdn.jsdelivr.net/selectivizr/1.0.3b/selectivizr.min.js net::ERR_FILE_NOT_FOUND

Please check console when you are developing

**Comment by Stanislava15** [comment]
Done
