### ISSUE TITLE
Starter block has empty line   

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/LoSo#5]

**Comment by Stanislava15** [comment]
I don't know what is "starter block". Could you expain me it?

**Comment by lapachuka** [comment]
![screen shot 2018-04-03 at 11 39 22 am](https://user-images.githubusercontent.com/2377964/38238806-b2d66b7a-3733-11e8-8791-7d61cff58cb5.png)

**Comment by Stanislava15** [comment]
Oh, got it.

It was empty because, that look likes in the course. 
But I've wrote there some information =)

Done!
