### ISSUE TITLE
Watch the next video and after refactor your own Javascript code

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/LoSo#7]
https://www.youtube.com/watch?v=RMiTxHba5fo

**Comment by Stanislava15** [comment]
I've watched this video.....but, if to be honest, I don't understand 95% of information ((((

**Comment by lapachuka** [comment]
I see . Ok , that is why you need to come to office sometimes .

**Comment by Stanislava15** [comment]
I agree)
