### ISSUE TITLE
Install for yourself VS code . It gonna help you to write code better 

### ISSUE THREAD

**Issue by lapachuka** [Stanislava15/LoSo#8]
Please install vs code . Then watch couple of youtube video how to use it . 
After it write here the links what you have watched and what you have done  for your VS code

**Comment by Stanislava15** [comment]
I install VS Code and watched intro videos from official page....I'll continue watch the videos tomorrow.
Is VS Code better or powerful than Brackets?

**Comment by lapachuka** [comment]
I even don't know what is Brackets . But i'm sure that VS code is better ;D
